name: firestore_data_table_source
description: "A Flutter PaginatedDataTable that can fetch Firestore documents
  from a Query object and filter them using a provided function."
version: 0.0.1
homepage: "https://github.com/grlduarte"

environment:
  sdk: '>=2.17.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fake_cloud_firestore: ^2.4.8
